spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/console?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useAffectedRows=true&useSSL=false
    username: root
    password: root
mybatis:
  config-location: classpath*:mapper/*.xml
springdoc:
  swagger-ui:
    display-request-duration: true
      groups-order: asc
      display-operation-id: true
      operations-sorter: method
      use-root-path: true
config:
  test:
    one: 1